---
# Nova compute handler

- name: Restart Nova compute
  shell: service nova-compute restart

- name: Restart libvirt
  shell: service libvirt-bin restart

- name: Restart Ceph
  shell: initctl restart ceph-all
