---
# Install Nova controller

- name: Create Nova DB
  mysql_db:
    login_host: "{{ openstack_database_ip }}"
    login_user: root
    login_password: "{{ database_root_password }}"
    name: nova
    state: present
  when: require_db_settings

- name: Add user to DB
  mysql_user:
    login_port: "{{ mysql_port }}"
    login_user: root
    login_password: "{{ database_root_password }}"
    host: "{{ item }}"
    user: nova
    password: "{{ nova_db_password }}"
    priv: "nova.*:ALL"
  with_items:
    - "localhost"
    - "%"
  when: require_db_settings

- name: Check Nova user existence
  shell: |
    export LC_ALL=C
    export OS_PROJECT_DOMAIN_ID=default
    export OS_USER_DOMAIN_ID=default
    export OS_PROJECT_NAME=admin
    export OS_TENANT_NAME=admin
    export OS_USERNAME=admin
    export OS_PASSWORD={{ openstack_admin_password }}
    export OS_AUTH_URL=http://{{ keystone_ip }}:35357/v3
    openstack user list | grep -q nova
  register: is_nova_exist
  ignore_errors: True
  changed_when: False
  when: require_db_settings

- name: Add Nova user,role,service and endpoint
  shell: |
    export LC_ALL=C
    export OS_PROJECT_DOMAIN_ID=default
    export OS_USER_DOMAIN_ID=default
    export OS_PROJECT_NAME=admin
    export OS_TENANT_NAME=admin
    export OS_USERNAME=admin
    export OS_PASSWORD={{ openstack_admin_password }}
    export OS_AUTH_URL=http://{{ keystone_ip }}:35357/v3
    openstack user create --project service --password {{ nova_password }} nova
    openstack role add --project service --user nova admin
    openstack service create --name nova --description "OpenStack Compute" compute
    openstack endpoint create --publicurl http://{{ nova_ip }}:8774/v2/%\(tenant_id\)s --internalurl http://{{ nova_ip }}:8774/v2/%\(tenant_id\)s --adminurl http://{{ nova_ip }}:8774/v2/%\(tenant_id\)s --region RegionOne compute
  when: require_db_settings and is_nova_exist|failed
  changed_when: False

- name: Install Nova packages
  apt: name="{{ item }}"
  with_items:
    - nova-api
    - nova-cert
    - nova-conductor
    - nova-consoleauth
    - nova-novncproxy
    - nova-scheduler
    - python-novaclient

- name: Set Nova configuration
  shell: |
    cp /etc/nova/nova.conf /etc/nova/nova.conf.prev
    crudini --set /etc/nova/nova.conf DEFAULT debug {{ nova_conf_debug }}
    crudini --set /etc/nova/nova.conf DEFAULT verbose {{ nova_conf_verbose }}
    crudini --set /etc/nova/nova.conf DEFAULT rpc_response_timeout {{ nova_rpc_response_timeout }}
    crudini --set /etc/nova/nova.conf DEFAULT ec2_listen_port {{ nova_ec2_port }}
    crudini --set /etc/nova/nova.conf DEFAULT osapi_compute_listen_port {{ nova_compute_port }}
    crudini --set /etc/nova/nova.conf DEFAULT metadata_listen_port {{ nova_metadata_port }}
    crudini --set /etc/nova/nova.conf DEFAULT novncproxy_port {{ nova_novncproxy_port }}
    crudini --set /etc/nova/nova.conf database connection mysql://nova:{{ nova_db_password }}@{{ openstack_database_ip }}/nova
    crudini --set /etc/nova/nova.conf DEFAULT rpc_backend rabbit
    crudini --set /etc/nova/nova.conf oslo_messaging_rabbit rabbit_host {{ openstack_messaging_ip }}
    crudini --set /etc/nova/nova.conf oslo_messaging_rabbit rabbit_userid {{ messaging_user }}
    crudini --set /etc/nova/nova.conf oslo_messaging_rabbit rabbit_password {{ messaging_password }}
    crudini --set /etc/nova/nova.conf DEFAULT auth_strategy keystone
    crudini --set /etc/nova/nova.conf keystone_authtoken auth_uri http://{{ keystone_ip }}:5000
    crudini --set /etc/nova/nova.conf keystone_authtoken auth_url http://{{ keystone_ip }}:35357
    crudini --set /etc/nova/nova.conf keystone_authtoken auth_plugin password
    crudini --set /etc/nova/nova.conf keystone_authtoken project_domain_id default
    crudini --set /etc/nova/nova.conf keystone_authtoken user_domain_id default
    crudini --set /etc/nova/nova.conf keystone_authtoken project_name service
    crudini --set /etc/nova/nova.conf keystone_authtoken username nova
    crudini --set /etc/nova/nova.conf keystone_authtoken password {{ nova_password }}
    crudini --set /etc/nova/nova.conf DEFAULT my_ip {{ my_ip }}
    crudini --set /etc/nova/nova.conf DEFAULT vnc_enabled True
    crudini --set /etc/nova/nova.conf DEFAULT vncserver_listen 0.0.0.0
    crudini --set /etc/nova/nova.conf DEFAULT vncserver_proxyclient_address {{ my_ip }}
    crudini --set /etc/nova/nova.conf DEFAULT novncproxy_base_url http://{{ nova_ip }}:6080/vnc_auto.html
    crudini --set /etc/nova/nova.conf DEFAULT network_api_class nova.network.neutronv2.api.API
    crudini --set /etc/nova/nova.conf DEFAULT security_group_api neutron
    crudini --set /etc/nova/nova.conf DEFAULT linuxnet_interface_driver nova.network.linux_net.LinuxOVSInterfaceDriver
    crudini --set /etc/nova/nova.conf DEFAULT firewall_driver nova.virt.firewall.NoopFirewallDriver
    crudini --set /etc/nova/nova.conf neutron url http://{{ neutron_ip }}:9696
    crudini --set /etc/nova/nova.conf neutron auth_strategy keystone
    crudini --set /etc/nova/nova.conf neutron admin_auth_url http://{{ keystone_ip }}:35357/v2.0
    crudini --set /etc/nova/nova.conf neutron admin_tenant_name service
    crudini --set /etc/nova/nova.conf neutron admin_username neutron
    crudini --set /etc/nova/nova.conf neutron admin_password {{ neutron_password }}
    crudini --set /etc/nova/nova.conf glance host {{ glance_ip }}
    crudini --set /etc/nova/nova.conf oslo_concurrency lock_path /var/lib/nova/tmp
    crudini --set /etc/nova/nova.conf neutron service_metadata_proxy True
    crudini --set /etc/nova/nova.conf neutron metadata_proxy_shared_secret {{ metadata_proxy_shared_secret }}
    crudini --set /etc/nova/nova.conf DEFAULT osapi_compute_workers 1
    crudini --set /etc/nova/nova.conf DEFAULT ec2_workers 1
    crudini --set /etc/nova/nova.conf DEFAULT metadata_workers 1
    crudini --set /etc/nova/nova.conf conductor workers 1
  changed_when: False

- name: Check Nova configuration modification
  shell: diff -u /etc/nova/nova.conf.prev /etc/nova/nova.conf
  register: equal
  ignore_errors: True
  changed_when: equal|failed
  notify:
    - Restart Nova

- name: Check Nova DB table existence
  shell: mysql -h {{ openstack_database_ip }} -uroot -p{{ mysql_root_password }} nova -e "show tables;" | grep -q nova
  register: is_table_exist
  ignore_errors: True
  changed_when: False
  when: require_db_settings

- name: Populate the Compute database
  shell: nova-manage db sync
  sudo_user: nova
  when: require_db_settings and is_table_exist|failed

- name: Remove unused SQLite database
  file: path=/var/lib/nova/nova.sqlite state=absent
  ignore_errors: True

- name: Disable nova-consoleauth autostart
  service: name=nova-consoleauth enabled=no

- name: Create openstack OCF directory
  file: path=/usr/lib/ocf/resource.d/openstack state=directory mode=0755

- name: Install nova-consoleauth OCF file
  # https://raw.github.com/madkiss/openstack-resource-agents/master/ocf/nova-consoleauth
  copy: src=nova-consoleauth dest=/usr/lib/ocf/resource.d/openstack/nova-consoleauth mode=0755

- name: Create CRM build directory
  file: path=/root/crm state=directory mode=0755

- name: Install crm settings
  copy: src=nova-consoleauth-cluster.crm.part dest=/root/crm/nova-consoleauth-cluster.crm.part
  notify: Register CRM
  when: require_crm_settings
