---
# Neutron network handler

- name: Restart Neutron network
  shell: >-
    initctl restart openvswitch-switch &&
    initctl restart neutron-plugin-openvswitch-agent &&
    initctl restart neutron-l3-agent &&
    initctl restart neutron-dhcp-agent &&
    initctl restart neutron-metadata-agent
