---
# Common task

- name: Upgrade default package
  apt: upgrade=yes update_cache=yes cache_valid_time=86400

- name: Install ntpd
  apt: name=ntp

- name: Install hosts
  template: src=hosts.j2 dest=/etc/hosts

- name: Add authorized key
  authorized_key: user=vagrant key="{{ lookup('file', 'cluster_id_rsa.pub') }}"
