---
# Setup RabbitMQ

- name: Check RabbitMQ exist
  shell: test -x /usr/sbin/rabbitmq-server
  register: is_exist
  ignore_errors: True

- name: Create RabbitMQ configuration directory
  file: path=/etc/rabbitmq state=directory owner=root group=root mode=0755

- name: Install RabbitMQ configuration
  template: src=rabbitmq.config.j2 dest=/etc/rabbitmq/rabbitmq.config
  notify: Restart RabbitMQ

- name: Install RabbitMQ server
  apt: name=rabbitmq-server

- name: Enable rabbitmq_management
  shell: |
    rabbitmq-plugins enable rabbitmq_management
    service rabbitmq-server stop
    sleep 5
  notify: Restart RabbitMQ
  when: is_exist|failed

- name: Install common cookie
  copy: src=dot.erlang.cookie dest=/var/lib/rabbitmq/.erlang.cookie owner=rabbitmq group=rabbitmq mode=0400
  notify: Restart RabbitMQ
  when: is_exist|failed
