---
# Neutron compute handler

- name: Restart Neutron compute
  shell: >-
    initctl restart openvswitch-switch &&
    initctl restart neutron-plugin-openvswitch-agent

- name: Run sysctl for neutron-compute
  shell: sysctl -p
