---
# Install Nova compute

- name: Install Nova packages
  apt: name="{{ item }}"
  with_items:
    - nova-compute
    - sysfsutils

- name: Set Nova configuration
  shell: |
    cp /etc/nova/nova.conf /etc/nova/nova.conf.prev
    crudini --set /etc/nova/nova.conf DEFAULT debug {{ nova_compute_conf_debug }}
    crudini --set /etc/nova/nova.conf DEFAULT verbose {{ nova_compute_conf_verbose }}
    crudini --set /etc/nova/nova.conf DEFAULT rpc_response_timeout {{ nova_compute_rpc_response_timeout }}
    crudini --set /etc/nova/nova.conf DEFAULT rpc_backend rabbit
    crudini --set /etc/nova/nova.conf oslo_messaging_rabbit rabbit_host {{ openstack_messaging_ip }}
    crudini --set /etc/nova/nova.conf oslo_messaging_rabbit rabbit_userid {{ messaging_user }}
    crudini --set /etc/nova/nova.conf oslo_messaging_rabbit rabbit_password {{ messaging_password }}
    crudini --set /etc/nova/nova.conf DEFAULT auth_strategy keystone
    crudini --set /etc/nova/nova.conf keystone_authtoken auth_uri http://{{ keystone_ip }}:5000
    crudini --set /etc/nova/nova.conf keystone_authtoken auth_url http://{{ keystone_ip }}:35357
    crudini --set /etc/nova/nova.conf keystone_authtoken auth_plugin password
    crudini --set /etc/nova/nova.conf keystone_authtoken project_domain_id default
    crudini --set /etc/nova/nova.conf keystone_authtoken user_domain_id default
    crudini --set /etc/nova/nova.conf keystone_authtoken project_name service
    crudini --set /etc/nova/nova.conf keystone_authtoken username nova
    crudini --set /etc/nova/nova.conf keystone_authtoken password {{ nova_password }}
    crudini --set /etc/nova/nova.conf DEFAULT my_ip {{ my_ip }}
    crudini --set /etc/nova/nova.conf DEFAULT vnc_enabled True
    crudini --set /etc/nova/nova.conf DEFAULT vncserver_listen 0.0.0.0
    crudini --set /etc/nova/nova.conf DEFAULT vncserver_proxyclient_address {{ my_ip }}
    crudini --set /etc/nova/nova.conf DEFAULT novncproxy_base_url http://{{ nova_ip }}:6080/vnc_auto.html
    crudini --set /etc/nova/nova.conf glance host {{ glance_ip }}
    crudini --set /etc/nova/nova.conf oslo_concurrency lock_path /var/lib/nova/tmp
    cp /etc/nova/nova-compute.conf /etc/nova/nova-compute.conf.prev
    crudini --set /etc/nova/nova-compute.conf libvirt virt_type qemu
    crudini --set /etc/nova/nova-compute.conf libvirt images_type rbd
    crudini --set /etc/nova/nova-compute.conf libvirt images_rbd_pool vms
    crudini --set /etc/nova/nova-compute.conf libvirt images_rbd_ceph_conf /etc/ceph/ceph.conf
    crudini --set /etc/nova/nova-compute.conf libvirt rbd_user cinder
    crudini --set /etc/nova/nova-compute.conf libvirt rbd_secret_uuid 57090ca8-c135-4349-b3d1-10d12467e081
    crudini --set /etc/nova/nova-compute.conf libvirt disk_cachemodes "network=writeback"
    crudini --set /etc/nova/nova-compute.conf libvirt inject_password false
    crudini --set /etc/nova/nova-compute.conf libvirt inject_key false
    crudini --set /etc/nova/nova-compute.conf libvirt inject_partition -2
    crudini --set /etc/nova/nova-compute.conf libvirt live_migration_flag "VIR_MIGRATE_UNDEFINE_SOURCE,VIR_MIGRATE_PEER2PEER,VIR_MIGRATE_LIVE,VIR_MIGRATE_PERSIST_DEST,VIR_MIGRATE_TUNNELLED"
    # enable discard support (be careful of performance)
    crudini --set /etc/nova/nova-compute.conf libvirt hw_disk_discard unmap
    crudini --set /etc/nova/nova.conf DEFAULT network_api_class nova.network.neutronv2.api.API
    crudini --set /etc/nova/nova.conf DEFAULT security_group_api neutron
    crudini --set /etc/nova/nova.conf DEFAULT linuxnet_interface_driver nova.network.linux_net.LinuxOVSInterfaceDriver
    crudini --set /etc/nova/nova.conf DEFAULT firewall_driver nova.virt.firewall.NoopFirewallDriver
    crudini --set /etc/nova/nova.conf neutron url http://{{ neutron_ip }}:9696
    crudini --set /etc/nova/nova.conf neutron auth_strategy keystone
    crudini --set /etc/nova/nova.conf neutron admin_auth_url http://{{ keystone_ip }}:35357/v2.0
    crudini --set /etc/nova/nova.conf neutron admin_tenant_name service
    crudini --set /etc/nova/nova.conf neutron admin_username neutron
    crudini --set /etc/nova/nova.conf neutron admin_password {{ neutron_password }}
  changed_when: False

- name: Check Nova configuration modification
  shell: diff -u /etc/nova/nova.conf.prev /etc/nova/nova.conf && diff -u /etc/nova/nova-compute.conf.prev /etc/nova/nova-compute.conf
  register: equal
  ignore_errors: True
  changed_when: equal|failed
  notify:
    - Restart Nova
    - Restart Nova compute

- name: Remove unused SQLite database
  file: path=/var/lib/nova/nova.sqlite state=absent
  ignore_errors: True

- name: Disable nova-compute autostart
  service: name=nova-compute enabled=no

- name: Create openstack OCF directory
  file: path=/usr/lib/ocf/resource.d/openstack state=directory mode=0755

- name: Install nova-compute OCF file
  copy: src=nova-compute dest=/usr/lib/ocf/resource.d/openstack/nova-compute mode=0755

- name: Create CRM build directory
  file: path=/root/crm state=directory mode=0755

- name: Install crm settings
  copy: src=nova-compute.crm.part dest=/root/crm/nova-compute.crm.part
  notify: Register CRM
  when: require_crm_settings
