---
# Install Nova compute

- name: Install Nova packages
  apt: name="{{ item }}"
  with_items:
    - nova-compute
    - sysfsutils

- name: Set Nova configuration
  shell: |
    cp /etc/nova/nova.conf /etc/nova/nova.conf.prev
    crudini --set /etc/nova/nova.conf DEFAULT debug True
    crudini --set /etc/nova/nova.conf DEFAULT verbose True
    crudini --set /etc/nova/nova.conf DEFAULT rpc_backend rabbit
    crudini --set /etc/nova/nova.conf oslo_messaging_rabbit rabbit_host {{ openstack_messaging_ip }}
    crudini --set /etc/nova/nova.conf oslo_messaging_rabbit rabbit_userid {{ messaging_user }}
    crudini --set /etc/nova/nova.conf oslo_messaging_rabbit rabbit_password {{ messaging_password }}
    crudini --set /etc/nova/nova.conf DEFAULT auth_strategy keystone
    crudini --set /etc/nova/nova.conf keystone_authtoken auth_uri http://{{ keystone_ip }}:5000
    crudini --set /etc/nova/nova.conf keystone_authtoken auth_url http://{{ keystone_ip }}:35357
    crudini --set /etc/nova/nova.conf keystone_authtoken auth_plugin password
    crudini --set /etc/nova/nova.conf keystone_authtoken project_domain_id default
    crudini --set /etc/nova/nova.conf keystone_authtoken user_domain_id default
    crudini --set /etc/nova/nova.conf keystone_authtoken project_name service
    crudini --set /etc/nova/nova.conf keystone_authtoken username nova
    crudini --set /etc/nova/nova.conf keystone_authtoken password {{ nova_password }}
    crudini --set /etc/nova/nova.conf DEFAULT my_ip {{ my_ip }}
    crudini --set /etc/nova/nova.conf DEFAULT vnc_enabled True
    crudini --set /etc/nova/nova.conf DEFAULT vncserver_listen 0.0.0.0
    crudini --set /etc/nova/nova.conf DEFAULT vncserver_proxyclient_address {{ my_ip }}
    crudini --set /etc/nova/nova.conf DEFAULT novncproxy_base_url http://{{ nova_ip }}:6080/vnc_auto.html
    crudini --set /etc/nova/nova.conf glance host {{ glance_ip }}
    crudini --set /etc/nova/nova.conf oslo_concurrency lock_path /var/lib/nova/tmp
    cp /etc/nova/nova-compute.conf /etc/nova/nova-compute.conf.prev
    crudini --set /etc/nova/nova-compute.conf libvirt virt_type qemu
  changed_when: False

- name: Check Nova configuration modification
  shell: diff -u /etc/nova/nova.conf.prev /etc/nova/nova.conf && diff -u /etc/nova/nova-compute.conf.prev /etc/nova/nova-compute.conf
  register: equal
  ignore_errors: True
  changed_when: equal|failed
  notify:
    - Restart Nova
    - Restart Nova compute

- name: Remove unused SQLite database
  file: path=/var/lib/nova/nova.sqlite state=absent
  ignore_errors: True
