---
# Install Neutron networking

- name: Change kernel networking function
  lineinfile: dest=/etc/sysctl.conf line="{{ item }}"
  with_items:
    - net.ipv4.ip_forward=1
    - net.ipv4.conf.all.rp_filter=0
    - net.ipv4.conf.default.rp_filter=0
  notify:
    - Run sysctl for neutron-networking

- name: Install Neutron packages
  apt: name="{{ item }}"
  with_items:
    - neutron-plugin-ml2
    - neutron-plugin-openvswitch-agent
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent

- name: Set Neutron configuration
  shell: |
    cp /etc/neutron/neutron.conf /etc/neutron/neutron.conf.prev
    crudini --set /etc/neutron/neutron.conf DEFAULT debug {{ neutron_network_conf_debug }}
    crudini --set /etc/neutron/neutron.conf DEFAULT verbose {{ neutron_network_conf_verbose }}
    crudini --set /etc/neutron/neutron.conf DEFAULT rpc_response_timeout {{ neutron_network_rpc_response_timeout }}
    crudini --set /etc/neutron/neutron.conf DEFAULT rpc_backend rabbit
    crudini --set /etc/neutron/neutron.conf oslo_messaging_rabbit rabbit_host {{ openstack_messaging_ip }}
    crudini --set /etc/neutron/neutron.conf oslo_messaging_rabbit rabbit_userid {{ messaging_user }}
    crudini --set /etc/neutron/neutron.conf oslo_messaging_rabbit rabbit_password {{ messaging_password }}
    crudini --set /etc/neutron/neutron.conf DEFAULT auth_strategy keystone
    crudini --set /etc/neutron/neutron.conf keystone_authtoken auth_uri http://{{ keystone_ip }}:5000
    crudini --set /etc/neutron/neutron.conf keystone_authtoken auth_url http://{{ keystone_ip }}:35357
    crudini --set /etc/neutron/neutron.conf keystone_authtoken auth_plugin password
    crudini --set /etc/neutron/neutron.conf keystone_authtoken project_domain_id default
    crudini --set /etc/neutron/neutron.conf keystone_authtoken user_domain_id default
    crudini --set /etc/neutron/neutron.conf keystone_authtoken project_name service
    crudini --set /etc/neutron/neutron.conf keystone_authtoken username neutron
    crudini --set /etc/neutron/neutron.conf keystone_authtoken password {{ neutron_password }}
    crudini --set /etc/neutron/neutron.conf DEFAULT core_plugin ml2
    crudini --set /etc/neutron/neutron.conf DEFAULT service_plugins router
    crudini --set /etc/neutron/neutron.conf DEFAULT allow_overlapping_ips True
    crudini --set /etc/neutron/neutron.conf DEFAULT allow_automatic_l3agent_failover True
    cp  /etc/neutron/plugins/ml2/ml2_conf.ini  /etc/neutron/plugins/ml2/ml2_conf.ini.prev
    crudini --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2 type_drivers flat,vlan,gre,vxlan
    crudini --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2 tenant_network_types gre
    crudini --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2 mechanism_drivers openvswitch
    crudini --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2_type_flat flat_networks external
    crudini --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2_type_gre tunnel_id_ranges 1:1000
    crudini --set /etc/neutron/plugins/ml2/ml2_conf.ini securitygroup enable_security_group True
    crudini --set /etc/neutron/plugins/ml2/ml2_conf.ini securitygroup enable_ipset True
    crudini --set /etc/neutron/plugins/ml2/ml2_conf.ini securitygroup firewall_driver neutron.agent.linux.iptables_firewall.OVSHybridIptablesFirewallDriver
    crudini --set /etc/neutron/plugins/ml2/ml2_conf.ini ovs local_ip {{ my_ip }}
    crudini --set /etc/neutron/plugins/ml2/ml2_conf.ini ovs bridge_mappings external:br-ex
    crudini --set /etc/neutron/plugins/ml2/ml2_conf.ini agent tunnel_types gre
    cp /etc/neutron/l3_agent.ini /etc/neutron/l3_agent.ini.prev
    crudini --set /etc/neutron/l3_agent.ini DEFAULT debug {{ neutron_l3_conf_debug }}
    crudini --set /etc/neutron/l3_agent.ini DEFAULT verbose {{ neutron_l3_conf_verbose }}
    crudini --set /etc/neutron/l3_agent.ini DEFAULT interface_driver neutron.agent.linux.interface.OVSInterfaceDriver
    crudini --set /etc/neutron/l3_agent.ini DEFAULT external_network_bridge ""
    crudini --set /etc/neutron/l3_agent.ini DEFAULT router_delete_namespaces True
    cp /etc/neutron/dhcp_agent.ini /etc/neutron/dhcp_agent.ini.prev
    crudini --set /etc/neutron/dhcp_agent.ini DEFAULT debug {{ neutron_dhcp_conf_debug }}
    crudini --set /etc/neutron/dhcp_agent.ini DEFAULT verbose {{ neutron_dhcp_conf_verbose }}
    crudini --set /etc/neutron/dhcp_agent.ini DEFAULT interface_driver neutron.agent.linux.interface.OVSInterfaceDriver
    crudini --set /etc/neutron/dhcp_agent.ini DEFAULT dhcp_driver neutron.agent.linux.dhcp.Dnsmasq
    crudini --set /etc/neutron/dhcp_agent.ini DEFAULT dhcp_delete_namespaces True
    crudini --set /etc/neutron/dhcp_agent.ini DEFAULT dnsmasq_config_file /etc/neutron/dnsmasq-neutron.conf
    if [ ! -f /etc/neutron/dnsmasq-neutron.conf ]; then
      echo 'dhcp-option-force=26,1454' > /etc/neutron/dnsmasq-neutron.conf
      pkill dnsmasq
    fi
    cp /etc/neutron/metadata_agent.ini /etc/neutron/metadata_agent.ini.prev
    crudini --set /etc/neutron/metadata_agent.ini DEFAULT debug {{ neutron_metadata_conf_debug }}
    crudini --set /etc/neutron/metadata_agent.ini DEFAULT verbose {{ neutron_metadata_conf_verbose }}
    crudini --set /etc/neutron/metadata_agent.ini DEFAULT auth_uri http://{{ keystone_ip }}:5000
    crudini --set /etc/neutron/metadata_agent.ini DEFAULT auth_url http://{{ keystone_ip }}:35357
    crudini --set /etc/neutron/metadata_agent.ini DEFAULT auth_region RegionOne
    crudini --set /etc/neutron/metadata_agent.ini DEFAULT auth_plugin password
    crudini --set /etc/neutron/metadata_agent.ini DEFAULT project_domain_id default
    crudini --set /etc/neutron/metadata_agent.ini DEFAULT user_domain_id default
    crudini --set /etc/neutron/metadata_agent.ini DEFAULT project_name service
    crudini --set /etc/neutron/metadata_agent.ini DEFAULT username neutron
    crudini --set /etc/neutron/metadata_agent.ini DEFAULT password {{ neutron_password }}
    crudini --set /etc/neutron/metadata_agent.ini DEFAULT nova_metadata_ip {{ nova_ip }}
    crudini --set /etc/neutron/metadata_agent.ini DEFAULT metadata_proxy_shared_secret {{ metadata_proxy_shared_secret }}
  changed_when: False

- name: Check Neutron configuration modification
  shell: >-
    diff -u /etc/neutron/neutron.conf.prev /etc/neutron/neutron.conf &&
    diff -u /etc/neutron/plugins/ml2/ml2_conf.ini.prev /etc/neutron/plugins/ml2/ml2_conf.ini &&
    diff -u /etc/neutron/l3_agent.ini.prev  /etc/neutron/l3_agent.ini &&
    diff -u /etc/neutron/dhcp_agent.ini.prev  /etc/neutron/dhcp_agent.ini &&
    diff -u /etc/neutron/metadata_agent.ini.prev /etc/neutron/metadata_agent.ini
  register: equal
  ignore_errors: True
  changed_when: equal|failed
  notify:
    - Restart Neutron network

- name: Check br-int
  shell: ovs-vsctl list-br | grep -q br-int
  register: result
  ignore_errors: True
  changed_when: False

- name: Add br-int
  shell: ovs-vsctl add-br br-int
  when: result|failed

- name: Check br-ex
  shell: ovs-vsctl list-br | grep -q br-ex
  register: result
  ignore_errors: True
  changed_when: False

- name: Add br-ex
  shell: |
    ovs-vsctl add-br br-ex
    ovs-vsctl add-port br-ex {{ br_ex_interface }}
    ethtool -K {{ br_ex_interface }} gro off
  when: result|failed

- name: Disable metadata_agent autostart
  service: name=neutron-metadata-agent enabled=no

- name: Create openstack OCF directory
  file: path=/usr/lib/ocf/resource.d/openstack state=directory mode=0755

- name: Install neutron-metadata-agent OCF file
  # https://raw.github.com/madkiss/openstack-resource-agents/master/ocf/neutron-metadata-agent
  copy: src=neutron-metadata-agent dest=/usr/lib/ocf/resource.d/openstack/neutron-metadata-agent mode=0755

- name: Install crm settings
  copy: src=neutron-metadata-cluster.crm.part dest=/root/neutron-metadata-cluster.crm.part
  notify: Register CRM
  when: require_crm_settings
