---
# OpenStack client environment setup

- name: Install OpenStack client
  apt: name=python-openstackclient

- name: Create OpenStack utility script directory
  file: path=/home/vagrant/openstack state=directory owner=vagrant group=vagrant mode=0755

- name: Install environment variable setting scripts
  template: src={{ item }}.j2 dest=/home/vagrant/openstack/{{ item }} owner=vagrant group=vagrant mode=0644
  with_items:
    - admin-openrc.sh
    - demo-openrc.sh

- name: Install maintenance scripts
  template: src={{ item }}.j2 dest=/home/vagrant/openstack/{{ item }} owner=vagrant group=vagrant mode=0755
  with_items:
    - prepare-ceph.sh
    - create-sample-network.sh
    - delete-sample-network.sh
    - get-cirros-and-reg.sh
    - clear-logs.sh

- name: Run Ceph preparation script
  shell: /home/vagrant/openstack/prepare-ceph.sh > /home/vagrant/openstack/prepare-ceph.log 2>&1
  sudo_user: vagrant
  args:
    chdir: /home/vagrant/openstack
    creates: /home/vagrant/openstack/prepare-ceph.done
