---
# OpenStack servers

- hosts:
    - sv1
    - sv2
    - sv3
  roles:
    - add-percona-repo
    - add-openstack-kilo-repo
    - common
    - xtradb
    - rabbitmq
    - haproxy
    - corosync-pacemaker
  sudo: yes
